name: cat_vs_dog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0 # Cek versi terbaru di pub.dev
  image_picker: ^1.0.7 # Cek versi terbaru di pub.dev
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/cat_dog_model.tflite
    - assets/models/labels.txt
